server:
  port: 8000
spring:
  application:
    name: my-zuul-service

# 라우팅 등록
zuul:
  routes:
    first-service:
      path: /first-service/** # 8000/first-service 로 요청되면 8081 포트로
      url: http://localhost:8081
    second-service:
      path: /second-service/** # 8000/second-service 로 요청되면 8082 포트로
      url: http://localhost:8082
