spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCBk4+yQhfOxQryvZSqByL7huF81artqci5up1xJoZV1JIGyyuKuPfHVQIFoSasZiCpw9zaAGpnQ4NEBsXaSlG/rtPcC1VlhlyeBm59flC7aCKI3EjLz3cRJIKNxjYKBmCAAYLfiI8DaLWi+hBTNdxIUIuc3uVqlhHOSSyU/Dyst/2iYEk2dhgRMpjBAgxMIEx8TT8+NqNP033PP1IVw6QVkYu6Jofj2fTOaqxBjuov4LJ8niOCay5KZp1g3QnV5IYKgk3x1N75lv/cdtiQwUHZt8Ny7waAiQeIiSqyVRe81CTpQ2742dpLE0c6yQt3XYUregJ+0hiLmjgfwRDlguLpbE9IQrnIxio2YNlr7vp9ijROQ4XKbHTesa4DJv9TOkw='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBB6X2HE3T9mK//EW50fx43P2LmXU1rH4Uhzv6N1W+kniBYcyYHrvpXGFbbyfyubPwndKTb4NWPp3/meYMRSzHmpl8KsKHndpvUgCDmnNNcOxG9Ph+V/FlMuiqZav67M93sJZpU9Dv0mrWgDxN9oXltmno2greXD0GznSEp8k07AKT/IK//Ll3XgMrElFBgydCAqQTt8UyVGBrYJ2XdhEgPeadgiW9MM7c4HST1hI1dmwsVtPgS2Z5fLFZ30zYwy9e4y+YwwVBTDNMYl4RPOjTvHltkfo9Qfx3OGBMOCzHpHfrttBrjT8x+mEdwmvxFL2Qw6LohMu3u1dvaaSOaUL1gixYwjpeyRZfI4Y3L6rGfJZa/ICm9f88id7CZT7VB7vlZZEZz0lO6rABYGN8hRS/G0nt5HV3MXKyfLR8lEwZRVg=='

gateway:
  ip: 192.168.219.105

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is 비어있음.